---
title: "Advanced Dashboarding2"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    social: ["menu"]
    source_code: embed
    theme:
      version: 4
      bootswatch: sandstone
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(palmerpenguins)
library(plotly)
library(DT)
library(fontawesome)
data("penguins")
```


Plots {data-navmenu="Pages"}
========================================================================

sidebar {.sidebar}
------------------------------------------------------------------------
<!-- this is a comment
-->
### Penguin Stats

The number of penguins in the data is `r nrow(penguins)`

Row
------------------------------------------------------------------------

### Number of Penguins
```{r}
valueBox(nrow(penguins), icon = "fa-linux") ## fontawesome icon
```


## Column {.tabset}
------------------------------------------------------------------------

### Scatter Plot of bill length vs. bill depth (mm)

```{r}
## htmlwidgets.org - lots of options for cool plotting
a = penguins %>% ggplot(aes(x = bill_length_mm, y = bill_depth_mm, color = species))+
  geom_point() # scatterplot
ggplotly(a)
```


### Chart B

```{r}
penguins %>% ggplot(aes(x = body_mass_g, y = sex, fill = sex))+
  geom_boxplot()
```

### Chart C

```{r}
penguins %>% ggplot(aes(x = flipper_length_mm, fill = species))+
  geom_histogram()+
  facet_wrap(~species)
```

Data {data-navmenu="Pages"}
========================================================================

```{r}
## datatables.net - see more options
penguins %>% datatable(extensions = "Buttons",
                       options = list(dom = "Blfrtip",
                                      buttons = c("copy", "csv", "excel", "pdf", "print"))) 
                                #button, length, f__, row, table, i__, page
```

